get 'gitlab_mappings', to: 'gitlab_mappings#index'
get 'gitlab_mappings/data', to: 'gitlab_mappings#graph_data'
post 'gitlab_mappings/update', to: 'gitlab_mappings#update'
get 'gitlab_mappings/fetch_parent_group', to: 'gitlab_mappings#fetch_parent_group'
get 'gitlab_groups', to: 'gitlab_groups#index'
get 'gitlab_groups/:group_id/orphan_projects', to: 'gitlab_groups#orphan_projects'
